In [1]:
import numpy as np

# Sample data
data = np.array([
    [1, 10, 100],
    [2, 20, 200],
    [1, 30, 300],
    [2, 40, 400],
    [3, 50, 500]
])

# Column index for IDs
id_column_index = 0

# Get unique IDs
unique_ids = np.unique(data[:, id_column_index])

# Dictionary to store separated arrays
separated_arrays = {}

# Separate arrays based on IDs
for unique_id in unique_ids:
    separated_arrays[unique_id] = data[data[:, id_column_index] == unique_id]

# Print separated arrays
for unique_id, array in separated_arrays.items():
    print(f"ID {unique_id}:\n{array}\n")

ID 1:
[[  1  10 100]
 [  1  30 300]]

ID 2:
[[  2  20 200]
 [  2  40 400]]

ID 3:
[[  3  50 500]]



In [2]:
import polars as pl
preds = pl.read_csv(r"C:\Users\Robin\Downloads\pred_indicators_only_complications.csv")

In [3]:
predictions

NameError: name 'predictions' is not defined

In [4]:
from numpy import genfromtxt
from icu_benchmarks.models.alarm_metrics import silence_positives, fill_gaps, convert_to_alarm
import numpy as np

predictions_no_threshold = genfromtxt(r"C:\Users\Robin\Downloads\pred_indicators_only_complications.csv", delimiter=',')
predictions = predictions_no_threshold.copy()
# Define the threshold
threshold = 0.5

# Round predictions to 0 and 1 according to the threshold
predictions = np.where(predictions >= threshold, 1, 0)

# Column index for grouping
group_column_index = 0

# Get unique group values
unique_groups = np.unique(predictions[:, group_column_index])
# Dictionary to store grouped arrays
grouped_arrays = {}

unique_groups = np.unique(predictions[:, group_column_index])

modified_arrays = []
# print(predictions)
# Group arrays based on unique values in the group column
for group in unique_groups:
    group_array = predictions[predictions[:, group_column_index] == group]
    # print(f"Group {group} before modification:\n{group_array}\n")
    ground_truth = group_array[:, 2]
    predictions = group_array[:, 4]
    group_array[:, 4] = silence_positives(ground_truth, predictions)
    group_array[:, 4], group_array[:, 2] = fill_gaps(predictions, ground_truth)
    # print(f"Group {group} after modification:\n{group_array}\n")
    modified_arrays.append(group_array)

# Combine the modified arrays back into a single array
combined_array = np.vstack(modified_arrays)
# combined_array = np.delete(combined_array, 3, axis=1)

# print("Combined array:")
# print(combined_array)
# 
# print(f"ROC AUC: {roc_auc_score(predictions[:, 2], predictions[:, 4])}")
# print(f"ROC AUC: {roc_auc_score(combined_array[:, 2], combined_array[:, 4])}")
# print(f"Average precision: {average_precision_score(predictions[:, 2], predictions[:, 4])}")
# print(f"Average precision: {average_precision_score(combined_array[:, 2], combined_array[:, 4])}")

In [29]:
predictions_no_threshold

array([[4.200e+01, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       [4.200e+01, 1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       [4.200e+01, 2.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       ...,
       [1.044e+03, 1.730e+02, 1.000e+00, 4.100e-02, 9.590e-01],
       [1.044e+03, 1.740e+02, 1.000e+00, 2.700e-02, 9.730e-01],
       [1.044e+03, 1.750e+02, 1.000e+00, 2.000e-02, 9.800e-01]])

In [30]:
predictions

array([0, 0, 0, ..., 1, 1, 1])

In [5]:
import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import PrecisionRecallDisplay, RocCurveDisplay, average_precision_score, roc_auc_score

# Assuming predictions, combined_array, and predictions_no_threshold are already defined
# predictions[:, 2] is the ground truth
# predictions[:, 4] is the original predictions
# combined_array[:, 4] is the modified predictions
# predictions_no_threshold[:, 4] is the no_threshold predictions

# Calculate metrics
roc_auc_original = roc_auc_score(predictions[:, 2], predictions[:, 4])
roc_auc_modified = roc_auc_score(combined_array[:, 2], combined_array[:, 4])
roc_auc_no_threshold = roc_auc_score(predictions[:, 2], predictions_no_threshold[:, 4])
average_precision_original = average_precision_score(predictions[:, 2], predictions[:, 4])
average_precision_modified = average_precision_score(combined_array[:, 2], combined_array[:, 4])
average_precision_no_threshold = average_precision_score(predictions[:, 2], predictions_no_threshold[:, 4])

# Plot ROC curves
fig, (ax1, ax2) = plt.subplots(1, 2, figsize=(12, 6))

RocCurveDisplay.from_predictions(predictions[:, 2], predictions[:, 4], ax=ax1, name='Original')
RocCurveDisplay.from_predictions(combined_array[:, 2], combined_array[:, 4], ax=ax1, name='Modified')
RocCurveDisplay.from_predictions(predictions[:, 2], predictions_no_threshold[:, 4], ax=ax1, name='No Threshold')
ax1.set_title(f'ROC Curve\nOriginal AUC: {roc_auc_original:.2f}, Modified AUC: {roc_auc_modified:.2f}, No Threshold AUC: {roc_auc_no_threshold:.2f}')

# Plot PRC curves
PrecisionRecallDisplay.from_predictions(predictions[:, 2], predictions[:, 4], ax=ax2, name='Original')
PrecisionRecallDisplay.from_predictions(combined_array[:, 2], combined_array[:, 4], ax=ax2, name='Modified')
PrecisionRecallDisplay.from_predictions(predictions[:, 2], predictions_no_threshold[:, 4], ax=ax2, name='No Threshold')
ax2.set_title(f'Precision-Recall Curve\nOriginal AP: {average_precision_original:.2f}, Modified AP: {average_precision_modified:.2f}, No Threshold AP: {average_precision_no_threshold:.2f}')

plt.tight_layout()
plt.show()

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [58]:
from sklearn.metrics import PrecisionRecallDisplay, RocCurveDisplay



ImportError: cannot import name 'PrecisionRecallDisplay' from 'sklearn' (C:\Users\Robin\miniconda\envs\yaib_19\lib\site-packages\sklearn\__init__.py)

In [34]:
predictions

array([[4.200e+01, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       [4.200e+01, 1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       [4.200e+01, 2.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       ...,
       [1.044e+03, 1.730e+02, 1.000e+00, 4.100e-02, 9.590e-01],
       [1.044e+03, 1.740e+02, 1.000e+00, 2.700e-02, 9.730e-01],
       [1.044e+03, 1.750e+02, 1.000e+00, 2.000e-02, 9.800e-01]])

In [28]:
combined_array

array([[4.200e+01, 0.000e+00, 0.000e+00, 0.000e+00],
       [4.200e+01, 1.000e+00, 0.000e+00, 0.000e+00],
       [4.200e+01, 2.000e+00, 0.000e+00, 0.000e+00],
       ...,
       [1.044e+03, 1.730e+02, 1.000e+00, 1.000e+00],
       [1.044e+03, 1.740e+02, 1.000e+00, 1.000e+00],
       [1.044e+03, 1.750e+02, 1.000e+00, 1.000e+00]])

In [21]:
group_array

array([[1.044e+03, 0.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 1.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 2.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 3.000e+00, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 4.000e+00, 0.000e+00, 9.990e-01, 1.000e-03],
       [1.044e+03, 5.000e+00, 0.000e+00, 9.990e-01, 1.000e-03],
       [1.044e+03, 6.000e+00, 0.000e+00, 9.990e-01, 1.000e-03],
       [1.044e+03, 7.000e+00, 0.000e+00, 9.990e-01, 1.000e-03],
       [1.044e+03, 8.000e+00, 0.000e+00, 9.990e-01, 1.000e-03],
       [1.044e+03, 9.000e+00, 0.000e+00, 9.990e-01, 1.000e-03],
       [1.044e+03, 1.000e+01, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 1.100e+01, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 1.200e+01, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 1.300e+01, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 1.400e+01, 0.000e+00, 1.000e+00, 0.000e+00],
       [1.044e+03, 1.500e+01, 0.000e+00,

In [3]:
pred_len = 24
label_horizon = 6
ground_truth = np.zeros(pred_len, dtype=int)
ground_truth[-label_horizon:] = 1
print(f"Ground truth: {ground_truth}")

# Simulate the model predictions (for example, using random values between 0 and 1)
predictions = np.random.rand(pred_len)
threshold = 0.5
predictions = np.where(predictions >= threshold, 1, 0)
print(f"Unaltered predictions: {predictions}")

# grace_horizon > label_horizon that we want to consider (i.e., the number of hours before the actual complication when the model is allowed but not required to predict 1)
grace_horizon = label_horizon * 2
# For how long should the alarm be silenced?
silencing_length = label_horizon
predictions = silence_positives(ground_truth, predictions, grace_horizon=grace_horizon, silencing_length=silencing_length)
print(f"Silenced predictions: {predictions}")

# Fill gaps in the predictions: we also want to consider early predictions with the grace_horizon.
predictions = fill_gaps(predictions)
print(f"Filled + silenced predictions: {predictions}")

Ground truth: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1]
Unaltered predictions: [0 0 1 0 1 0 0 0 0 1 1 0 1 0 1 1 0 1 1 0 1 0 0 0]
Silenced predictions: [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 0 1 1 0 1 0 0 0]
Filled + silenced predictions: [0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 1 1 1 1 1 1 1 1 1]


NameError: name 'p' is not defined

In [7]:
preds.group_by("# id").map_groups(lambda group_df: pl.DataFrame(group_df["time"],convert_to_alarm(group_df["ground_truth"], group_df["prediction_1"])))

PanicException: UDF failed: data does not match the number of columns

In [6]:
preds

# id,time,ground_truth,prediction_0,prediction_1
i64,i64,f64,f64,f64
42,0,0.0,1.0,0.0
42,1,0.0,1.0,0.0
42,2,0.0,1.0,0.0
42,3,0.0,1.0,0.0
42,4,0.0,1.0,0.0
…,…,…,…,…
1044,171,1.0,0.006,0.994
1044,172,1.0,0.007,0.993
1044,173,1.0,0.041,0.959
